# Generated by Django 3.2.4 on 2021-08-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=54)),
                ('last_name', models.CharField(max_length=54)),
                ('email', models.EmailField(max_length=54)),
                ('subject', models.CharField(max_length=54)),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Received Messages',
            },
        ),
    ]
