# Generated by Django 3.2.4 on 2021-09-17 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessages',
            options={'verbose_name': 'Received Message'},
        ),
    ]
