# Generated by Django 3.2.4 on 2021-08-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('preview', models.TextField(blank=True, max_length=254, null=True)),
                ('article', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=54, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('blog_source', models.CharField(blank=True, max_length=254, null=True)),
                ('source_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
