# Generated by Django 3.2.4 on 2021-09-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='article',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(blank=True, default='', max_length=54),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_source',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='preview',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
    ]
