# Generated by Django 3.2.4 on 2021-07-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_clothing_size',
            new_name='has_sizing',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_footwear_size',
        ),
    ]
