# Generated by Django 3.2.4 on 2021-07-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210718_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_sizing',
            new_name='has_clothing_sizing',
        ),
        migrations.AddField(
            model_name='product',
            name='has_footwear_sizing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
